### ISSUE TITLE
.sync について

### ISSUE THREAD

**Issue by kazudeath1** [Kanatani28/zenn-content#4]
https://github.com/Kanatani28/zenn-content/blob/6dc5ba2eca8883b2c7175f8d9271812aa04aee4c/articles/compare_vue_and_react.md?plain=1#L287

https://v3.ja.vuejs.org/guide/migration/v-model.html#%E7%A7%BB%E8%A1%8C%E3%81%AE%E6%88%A6%E7%95%A5

廃止されたのではなく、書き方が統一されたのだと思いました〜

**Comment by Kanatani28** [comment]
@kazudeath1 
すいません、気付くのに時間がかかってしまいました:bow:
取り消し線入れておきました。
